### ISSUE TITLE
Replace tsdx use in build of the FDC3 NPM module

### ISSUE THREAD

**Issue by kriswest** [finos/FDC3#1061]
### Area of Issue
[x] API

~Upgrading tsdx to 0.13.3~ Replacing tsdx (used to bundle the FDC3 NPM module) would resolve 17 moderate vulnerabilities in the FDC3 repo and should ease future maintenance as tsdx is now unmaintained ([ref](https://github.com/jaredpalmer/tsdx/issues/1065)).

### npm audit report
```
jsdom  <=16.5.3
Severity: moderate
Insufficient Granularity of Access Control in JSDom - https://github.com/advisories/GHSA-f4c9-cqv8-9v98
Depends on vulnerable versions of request
Depends on vulnerable versions of request-promise-native
Depends on vulnerable versions of tough-cookie
fix available via `npm audit fix --force`
Will install tsdx@0.13.3, which is a breaking change
node_modules/jsdom
  jest-environment-jsdom  10.0.2 - 25.5.0
  Depends on vulnerable versions of jsdom
  node_modules/jest-environment-jsdom
    jest-config  12.1.1-alpha.2935e14d - 25.5.4
    Depends on vulnerable versions of @jest/test-sequencer
    Depends on vulnerable versions of jest-environment-jsdom
    Depends on vulnerable versions of jest-jasmine2
    node_modules/jest-config
      jest-cli  12.1.1-alpha.2935e14d || 12.1.2-alpha.6230044c - 25.5.4
      Depends on vulnerable versions of @jest/core
      Depends on vulnerable versions of jest-config
      node_modules/jest-cli
        jest  12.1.2-alpha.6230044c - 25.5.4
        Depends on vulnerable versions of @jest/core
        Depends on vulnerable versions of jest-cli
        node_modules/jest
          tsdx  >=0.14.0
          Depends on vulnerable versions of jest
          node_modules/tsdx
      jest-runner  21.0.0-alpha.1 - 25.5.4
      Depends on vulnerable versions of jest-config
      Depends on vulnerable versions of jest-jasmine2
      Depends on vulnerable versions of jest-runtime
      node_modules/jest-runner
        @jest/test-sequencer  <=25.5.4
        Depends on vulnerable versions of jest-runner
        Depends on vulnerable versions of jest-runtime
        node_modules/@jest/test-sequencer
      jest-runtime  12.1.1-alpha.2935e14d - 25.5.4
      Depends on vulnerable versions of jest-config
      node_modules/jest-runtime
        jest-jasmine2  24.2.0-alpha.0 - 25.5.4
        Depends on vulnerable versions of jest-runtime
        node_modules/jest-jasmine2

node-notifier  <8.0.1
Severity: moderate
OS Command Injection in node-notifier - https://github.com/advisories/GHSA-5fw9-fq32-wv5p
fix available via `npm audit fix --force`
Will install tsdx@0.13.3, which is a breaking change
node_modules/node-notifier
  @jest/reporters  <=26.4.0
  Depends on vulnerable versions of node-notifier
  node_modules/@jest/reporters
    @jest/core  <=25.5.4
    Depends on vulnerable versions of @jest/reporters
    Depends on vulnerable versions of jest-config
    Depends on vulnerable versions of jest-runner
    Depends on vulnerable versions of jest-runtime
    node_modules/@jest/core

request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
fix available via `npm audit fix --force`
Will install tsdx@0.13.3, which is a breaking change
node_modules/request
  request-promise-core  *
  Depends on vulnerable versions of request
  node_modules/request-promise-core
    request-promise-native  >=1.0.0
    Depends on vulnerable versions of request
    Depends on vulnerable versions of request-promise-core
    Depends on vulnerable versions of tough-cookie
    node_modules/request-promise-native

tough-cookie  <4.1.3
Severity: moderate
tough-cookie Prototype Pollution vulnerability - https://github.com/advisories/GHSA-72xf-g2v4-qvf3
fix available via `npm audit fix --force`
Will install tsdx@0.13.3, which is a breaking change
node_modules/request-promise-native/node_modules/tough-cookie
node_modules/request/node_modules/tough-cookie
node_modules/tough-cookie

17 moderate severity vulnerabilities
```

**Comment by novavi** [comment]
Hi @kriswest I was about to say I could potentially look at creating a PR for this (in advance of that other `Methods.ts` issue that we spoke about recently) but if I'm not misreading the situation - and it's entirely possible that I am - then it seems there might be few things to discuss first.

Even though this issue is described as requiring *upgrading* `tsdx` to 0.13.3, perhaps surprisingly and counterintuitively I think the npm audit report is actually suggesting *downgrading* tsdx to 0.13.3 - because in fact `@finos/fdc3` currently references ^0.14.1 for `tsdx`.

It _appears_ the root cause is that `tsdx` has a vulnerable version of `jsdom` as a transitive dependency. Now, downgrading a recently-released version of a package containing problems to a slightly-older but more stable version would seem acceptable (until a newer version became available). But in this particular case, it seems far from ideal that the proposed solution would be to downgrade from `tsdx0.14.1` (which is already nearly 3 years old, dating from 13 Oct 2020) to the even older `tsdx0.13.3` version (dating from 23 Aug 2020).

Given how long it has been since `tsdx` has had a new release, it might only be a matter of time before future npm audit reports start to highlight further vulnerabilities in transitive dependencies of _all_ versions of `tsdx`.  This raises the question of whether how long the `@finos/fdc3` package can realistically continue to use `tsdx`.  I must admit I haven't taken the time to read too widely about `tsdx` yet, but two relevant discussions I happened across are here:

[Is TSDX still maintained? #1065](https://github.com/jaredpalmer/tsdx/issues/1065)

[Move away from TSDX #3222](https://github.com/mobxjs/mobx/issues/3222)

Further, I also note that `@finos/fdc3` references `typescript@^4.0.3` in the `package.json`, which resolved to v4.9.4 in the `package-lock.json` (and would resolve to 4.9.5 if regenerated today). However, TypeScript v5.x has been available for 6 months now (the current version being v5.2.2). So purely to stay up to date (not because of vulnerabilities) this should probably also be in scope for review in a subsequent issue.

So I believe there might be two things here:

1. Look at whether the moderate vulnerabilities can easily be resolved by a change to the version of `tsdx`. This may or may not be as simple as making the change suggested (in my experience sometimes `npm audit fix --force` doesn't _always_ fix a problem as promised) plus the additional testing required.
2. Raise a new issue to review the use of `tsdx` and consider alternatives - _if_ `tsdx` is fact no longer maintained (TBC) and is considered likely to lead to bigger problems down the road.

I would imagine point 1 is probably still worth doing if there is in fact an easy resolution - even though it might well be superseded by point 2.

**I'm happy to raise a separate issue for point 2 if you think there is value in me exploring that in order to present options back to the standard working group and potentially subsequently create a PR containing a solution? (This is clearly a bigger task with wider implications and testing requirements than the one this issue was initially scoped for.)**

Coincidentally, right now I have an internal TypeScript package at work that I'm looking to move to a new bundling/packaging solution. I haven't done a proper analysis yet, but I have had a little play around with using Vite's Library Mode. Though I'd only previously used Vite in its more common incarnation as a direct replacement for CRA for scaffolding React apps, it seems like Vite Library Mode _might_ be a solution for TypeScript library bundling/packaging (two of the most obvious plus points being that it's actively maintained and it benefits from a large community). My review for my internal package solution will ultimately also encompass consideration of other alternatives, since one cannot justify making this type of change without undertaking the necessary due diligence. Therefore regardless of this `@finos/fdc3` package issue, I am expecting to be looking at this area over the next couple of weeks - and there might well be some relevant learning points and conclusions that will come out of this.

I'm interested in your thoughts on the long-term solution here anyway. And indeed from any of the other maintainers with recent experience and/or strong views on this space.

Clearly, `tsdx` was actively maintained and a sensible choice at the time the `@finos/fdc3` package was originally created a few years ago, but I must admit I don't anything of the background or whether any subsequent discussion about its usage has taken place since. Perhaps the wider issue of `tsdx` has already been discussed more recently elsewhere?

**Comment by kriswest** [comment]
@novavi Thanks for looking into this. I've gone ahead and renamed this issue - tsdx does look unmaintained and we don't want to be depending on it!

I'm not particularly familiar with `tsdx` and inherited the package.json scripts (presumably set-up by @rikoe originally) that use it to build the FDC3 npm module, as well as the [github action](https://github.com/finos/FDC3/blob/fdc3-charter-update/.github/workflows/package.yml) that use the `test`, `lint` and `build` scripts to prepare and publish the NPM module.  Hence, I've currently got no opinion on whether we move to [dts-cli](https://github.com/weiran-zsd/dts-cli), [vite](https://vitejs.dev/), plain [rollup](https://rollupjs.org/), [microbundle](https://github.com/developit/microbundle), [nx.dev](https://nx.dev/) or something else...

@rikoe @mattjamieson and other @finos/fdc3-maintainers do any of you have strong opinions on which way we should go?
My only strong opinions on this are that we need to ensure that the NPM module is as widely compatible as possible and that we should probably settle this before taking the 2.1 NPM module out of beta.

**Comment by kriswest** [comment]
P.S> no need to raise new issues - I think we could go straight to PRs from here.

**Comment by mattjamieson** [comment]
I'll try and have a look over the weekend

**Comment by novavi** [comment]
@kriswest @mattjamieson 

> no opinion on whether we move to [dts-cli](https://github.com/weiran-zsd/dts-cli), [vite](https://vitejs.dev/), plain [rollup](https://rollupjs.org/), [microbundle](https://github.com/developit/microbundle), [nx.dev](https://nx.dev/) or something else...

Yes, these are reasonable alternatives. `dts-cli` I have used before, and I did come across some weirdness with package imports with its default configuration at the time - although I'm sure it's probably better now. Since it's forked from `tsdx` that _ought_ to make it an easier proposition.  But if making this type of change then probably good to consider what the best alternative is for the long-term. In particular, lack of contributors on `dts-cli` relative to some alternatives might put us at risk of having to switch again in future if it became unmaintained.

P.S> no need to raise new issues - I think we could go straight to PRs from here.

Agreed. Now you've repurposed this issue into a more general "replace tsdx use" and stated that you want to resolve this prior to taking v2.1 package out of beta, this makes total sense.

**Comment by kriswest** [comment]
Apparently Vite has a library mode: https://andrewwalpole.com/blog/use-vite-for-javascript-libraries/

> I'll try and have a look over the weekend

Great @mattjamieson

**Comment by novavi** [comment]
@kriswest @mattjamieson Quick update on this - I did some work yesterday converting some TypeScript library projects from [dts-cli](https://github.com/weiran-zsd/dts-cli) to [Vite Library Mode](https://vitejs.dev/guide/build.html#library-mode). Going from a zero-config CLI, it did require a little bit extra in the way of config/setup for ESLint/Jest, but it seems to work pretty well for the scenarios I've tested so far. Those scenarios were essentially replacing `dts-cli` for build, watch task, lint, lint autofix, units tests, and coverage... for ESM and IIFE formats (I didn't have any UMD requirement).

I'm certainly not wedded to `Vite` as a bundling/packaging solution though, and @kriswest I appreciate you also referenced [dts-cli](https://github.com/weiran-zsd/dts-cli), [rollup](https://rollupjs.org/), [microbundle](https://github.com/developit/microbundle) and [nx.dev](https://nx.dev/).  One thing that stands out about `microbundle` is the gap between releases and the fact that it's a v0.x tool, which likely raises the risk profile of that solution a bit.  And as mentioned before, `dts-cli` also doesn't seem like a great option because of the lack of contributors.

I don't (yet) have a good enough perspective on vanilla `rollup` or `nx.dev`, but it seems like spikes on one of both of those would be the next logical step for me to take... unless someone has already done some of this analysis and already feels strongly at this point we should go in a particular direction?
