### ISSUE TITLE
NatWest Group FDC3 Use Case Exploration

### ISSUE THREAD

**Issue by mcleo-d** [finos/FDC3#1164]
Dear @finos/fdc3-maintainers,

NatWest Group has a number of financial services desktop and cross firm interoperability use cases that could fall into the scope of FDC3 that we'd like to discuss with the project before officially raising GitHub issues.

Please advise how you'd like to take the discussion forward as we're more than happy to host a small Chatham House Rule discussion in London or virtually over Zoom if a wider group would like to join.

Kind regards,

James.

**Comment by kriswest** [comment]
@mcleo-d I'd be happy to participate in such a discussion. We agreed, at the Standards Working Group meeting last week, to reboot the "Context & Intents Discussion Group" as the "FDC3 Use Cases and Workflows Discussion Group", which meets for the first time on Thursday 7th March. It would seem both a perfect fit for that discussion and an ideal way to kick off the new group if you're willing.

If that doesn't work, then I'm sure we can sort out an alternative date/time for such a discussion - it's been far too long since I've visited Bishopsgate!

**Comment by nkolba** [comment]
Count me in as well @mcleo-d.  (either w/ Context & Intents or separate is fine w/me).  Very happy to see use cases being raised.

**Comment by openfin-johans** [comment]
Sounds like a great idea - brings back memories from the good old use case working group and round-table discussions. Happy to join - ideally in person!

**Comment by mistryvinay** [comment]
@mcleo-d thank you for raising this issue. It's come at a good time as we reformat the current CD&I meetings.

I would like to take you up on the Chatham House discussion to understand more about the topics you would like to raise.  We can then look to add those as agenda items for the March 'FDC3 Use Cases and Workflows Discussion Group" meeting.

**Comment by mistryvinay** [comment]
@mcleo-d have included this issue in this months meeting #1168 

Look forward to seeing you at the meeting.

**Comment by mistryvinay** [comment]
@mcleo-d is this still of interest? I would be happy to arrange the gathering.

Alternatively would you like me to close this issue.

**Comment by kriswest** [comment]
Closed due to inactivity
