### ISSUE TITLE
Broken link in fdc3-intro.md

### ISSUE THREAD

**Issue by Juno-888** [finos/FDC3#1262]
The why FDC3 link in fdc3 introduction document cannot work. 
The location: https://github.com/finos/FDC3/blob/master/docs/fdc3-intro.md
 I think the link why-FDC3 is related to why-fdc3.md in the same folder. I am working on it by edit the documentation.

**Comment by Juno-888** [comment]
I will pr asap

**Comment by bingenito** [comment]
Hi @Juno-888, I'm not seeing this issue.  Could it be browser dependent?

**Comment by Juno-888** [comment]
Hi,I have tested it on both Mac and Windows, and it doesn't display in browsers on either operating system. All results are 404 not found.

**Comment by kriswest** [comment]
@Juno-888 Could you post the URL of the page where the link is and the link URL for the page that returns a 404 - there are multiple versions of most pages by Standard version so we may be looking at the wrong one...

**Comment by shijiadong2022** [comment]
The broken link is in the Motivation session of https://github.com/finos/FDC3/blob/master/docs/fdc3-intro.md
For more information, see [Why FDC3?](https://github.com/finos/FDC3/blob/main/docs/why-fdc3)
This links to a 404 page. It should be https://github.com/finos/FDC3/blob/main/docs/why-fdc3.md

**Comment by kriswest** [comment]
Aha @shijiadong2022 the github links explain it! The links _may_ not work in github as they are written for docusaurus to handle. The first page you linked is deployed here: https://fdc3.finos.org/docs/next/fdc3-intro and the link works, resulting in navigation to: https://fdc3.finos.org/docs/next/why-fdc3

We have a preview system set-up via netlify so that when a PR is raised a true preview of the docusaurus site is generated so we can review docs changes. These end up with similar URLs (posted in comments on the PR by netlify), e.g. https://deploy-preview-1233--fdc3.netlify.app/docs/next/fdc3-intro

As I think this now understood and not a problem I'll close this issue - please feel free to reopen if I've missed something (e.g if you were not looking at the github links/markdown previews @Juno-888).

Finally, if you are looking for somewhere to contribute to FDC3, plase feel free to get in touch with the maintainers at fdc3-maintainers@finos.org, or on slack. I'll make sure we take a look at tagging some more things with ['good first issue'](https://github.com/finos/FDC3/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)
