### ISSUE TITLE
Broken link in https://fdc3.finos.org/docs/next/api/spec

### ISSUE THREAD

**Issue by Juno-888** [finos/FDC3#1273]
The **Context** link in Implementation language session is invalid in https://fdc3.finos.org/docs/next/api/spec
After clicking the **Context** link in the image, it jumps to a incorrect URL(https://fdc3.finos.org/docs/next/api/ref/Context) with 404 page.
I think the correct URL reference should be https://fdc3.finos.org/docs/next/context/ref/Context.

You can refer to the snapshot below to find the issue：
![image](https://github.com/user-attachments/assets/5dcfa561-4e2e-48c5-932e-0ead5e140a6b)

I open a PR to edit. Free to get in touch with me.

**Comment by kriswest** [comment]
@Juno-888 you are correct that the link is wrong. 

However, we're going to get rid of the Context reference page shortly (in this [PR](https://github.com/finos/FDC3/pull/1252) - heres a [preview](https://deploy-preview-1252--fdc3.netlify.app/docs/next/context/spec)) and integrate it into the context overview (as `fdc3.context` is the base for other context types, rather than being a context type of its own). Hence, if you are going to raise a PR to fix this, can you link to the context overview instead please - I'd suggest this is the right link: https://fdc3.finos.org/docs/next/context/spec#the-context-interface which you would specify as `context/spec#the-context-interface` I think.

**Comment by kriswest** [comment]
closed as completed
