### ISSUE TITLE
Client-side example mistakenly refer to wrong name "symbol" in PrivateChannel doc

### ISSUE THREAD

**Issue by YaoYao-dd** [finos/FDC3#1279]
## Minor Issue
Client-side example mistakenly refer to wrong name "symbol" in PrivateChannel doc， it should be 'ticker'  like below.
```
const resolution3 = await fdc3.raiseIntent("QuoteStream", { type: "fdc3.instrument", id : { **ticker**: "AAPL" } });
    try {
```
for below reasons:

1.  make client-side and sever-side be consistent, both use 'ticker',
2.  content data standard also defines instrument type with 'ticker'.

### Area of Issue
[ ] App Directory
[*] API
[ ] Context Data
[ ] Intents
[ ] Desktop Agent Bridging
[ ] Use Cases
[ ] Other

**Comment by YaoYao-dd** [comment]
I can open PR to fix this if necessary, thanks.

**Comment by kriswest** [comment]
You are correct, there is an error here: https://github.com/finos/FDC3/blob/aaa2a803069649180751964b7e0f210dbd48b1f3/docs/api/ref/PrivateChannel.md?plain=1#L80

When raising a PR to fix this, it should also be fixed in past versions:
-  https://github.com/finos/FDC3/blob/aaa2a803069649180751964b7e0f210dbd48b1f3/website/versioned_docs/version-2.1/api/ref/PrivateChannel.md?plain=1#L80
- https://github.com/finos/FDC3/blob/aaa2a803069649180751964b7e0f210dbd48b1f3/website/versioned_docs/version-2.0/api/ref/PrivateChannel.md?plain=1#L75

And a Changelog entry in the FIxed section would also be appreciated: https://github.com/finos/FDC3/blob/main/CHANGELOG.md

**Comment by bingenito** [comment]
I verified the pending .NET sample in #1108 has Ticker as the ID property

**Comment by YaoYao-dd** [comment]
will raise PR, thanks @kriswest

**Comment by YaoYao-dd** [comment]
PR opened, https://github.com/finos/FDC3/pull/1314, thanks

**Comment by kriswest** [comment]
closed as completed
