### ISSUE TITLE
Simplify Web Connection Protocol

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#1301]
## Minor Issue

It's not clear why the web connection protocol is so "chatty" and contains so many steps.  And actually I think this might cause a problem in certain implementations (see below)

## Overview 

If I've understood correctly, this is the proposed flow (assuming we are communicating with an embedded iframe and not just a parent window):

```mermaid
sequenceDiagram
    participant AppA
    participant DesktopAgentIFrame
    participant DesktopAgent
    AppA->>DesktopAgent: WCP1Hello
    DesktopAgent ->> AppA: WCP2LoadURL
    note left of DesktopAgent: sends URL for embedded iframe
    note left of AppA: loads given URL
    AppA --> DesktopAgentIFrame: load
    DesktopAgentIFrame ->> AppA: WCP3Handshake 
    note left of DesktopAgentIFrame: contains channel selector url, intent resolver url, message port
    AppA->>DesktopAgentIFrame: WCP4Validate
    note right of AppA:  validate message now uses app's window.location.href to validate by default
    DesktopAgentIFrame ->> AppA: WCP5SuccessResponse 
    note left of DesktopAgentIFrame: returns appId, instanceId, Metadata
```

What would be a lot simpler is just to have the same information flowing back and forth but with fewer steps:

```mermaid
sequenceDiagram
    participant AppA
    participant DesktopAgentIFrame
    participant DesktopAgent
    AppA->>DesktopAgent: WCP1Hello
    note right of AppA:  validate message now uses app's window.location.href to validate by default
    DesktopAgent ->> AppA: WCP2LoadURL
    note left of DesktopAgent: sends URL for embedded iframe,  <br /> channel selector/ intent resolver urls,  appId, instanceId, Metadata
    note left of AppA: loads given URL
    AppA --> DesktopAgentIFrame: load
    DesktopAgentIFrame ->> AppA: WCP3Handshake 
    note left of DesktopAgentIFrame: contains message port
```

Although it being more complex isn't a problem _per se_, we should favour the simpler solution if possible.  

### Channel Selector/Intent Resolver Issue

What might be a problem is that we decide on the approach for channel selectors and intent resolvers up-front, before the apps identitiy is known.  I think this might be a problem:  I can see some apps might get started in iframes (possibly not needing a channel selector or intent resolver) and some might get started in tabs (and therefore needing both).  But the DA won't be aware of which case it is at the point at which it sends the message telling the app what to do.

**Comment by kriswest** [comment]
First off, don't forget the 'load something in an iframe step' `WCP2LoadURL` is optional and only used if the DA sends back a URL to load using that message, otherwise go straight to `WCP3Handshake`. Also, your diagram is missing the resend of WCP1Hello to the iFrame to restart the process with that. We may be able to eliminate that... but it creates some variation between cases that it might be better to avoid... However, if you've got data in session storage with the iframe URL  and you are reconnecting you can actually skip the first `WCP1Hello` and go straight to setting up the iframe.

As to your question, you're looking to drop the `WCP4Validate` step and to return the data from `WCP5ValidateAppIdentityResponse` in `WCP3Handshake`, right?

There are two possible issues that I see with that:

1. The reconnecting app would be sending over its identity details (including a secret) before knowing that what is on the other end is sending back valid Desktop Agent responses and it would be sending it over the `WindowProxy.postMessage` (easy for arbitrary code in the page to read via the global window object) rather than `messagePort.postMessage` (hard for arbitrary code to read). There is a very small amount of protection afforded by validating the message - but that could be strengthened in future (e.g. a uuid that the DA has to retain with the WindowProxy and send back). Using the `MessagePort` rather than the `WindowProxy` seems a good idea and leads on to the next point...
2. We are likely to want to add stronger security measures in future based on asymmetric encryption (using public keys that the Identity and Security discussion group is likely to recommend adding to appD records) - this would be better done over the MessagePort and after message validation.

We discussed 2 during past meetings when designing the WCP - its worth noting that there is a proposal to add the same id validation as an option through the API for containers... If we don't keep the extra step I strongly suspect we'll need to add it back in future.

**Comment by robmoffat** [comment]
> First off, don't forget the 'load something in an iframe step' WCP2LoadURL is optional and only ...

Yes, I know there are two routes - I am just showing one to make it a little clearer.

> Also, your diagram is missing the resend of WCP1Hello to the iFrame to restart the process with that. We may be able to eliminate that...

I think I've raised this before (though maybe not on GitHub) but this causes a race condition between the iframe loading and the message arriving.  It's better we don't have that step.

> .. However, if you've got data in session storage with the iframe URL and you are reconnecting you can actually skip the first WCP1Hello and go straight to setting up the iframe 

👍 

> The reconnecting app would be sending over its identity details ...

Yes, I did consider this yesterday.  I'm not sure there's really any security improvement by having multiple steps though.  A determined spoofer could just read the messages and respond as if it were a desktop agent.  But if you want to send all the appId/metadata through the message port, that could work..

> We are likely to want to add stronger security measures in future based on asymmetric encryption (using public keys that the Identity and Security discussion group is likely to recommend adding to appD records) - this would be better done over the MessagePort and after message validation.

Definitely agree.

> As to your question, you're looking to drop the WCP4Validate step and to return the data from WCP5ValidateAppIdentityResponse in WCP3Handshake, right?

So to summarise
1. App Starts, sending: 
      - WCP1Hello adding the URL of the app, as discussed in the last meeting.  (i.e. so we don't need WCP4Validate)
2. DA then optionally sends: 
      - WCP2LoadURL (with a url, which gets loaded)
3. DA or iFrame then sends:
     - WCP3Handshake (containing a message port, channel selector, intent resolver URLs, appId, instanceId, metadata etc.)

Thinking about the security step a few ideas:
 - this is likely to have to work as a challenge-response, where the DA sends a message challenging the App to prove it's identity (encrypt this string for me using your private key) and the app responds.  
 - If we did that, it would definitely have to come after WCP1Hello, otherwise the DA won't know which app it's communicating with.    
 - We could potentially do that on a periodic basis?  
 - Would the app also want to issue a challenge/response to the DA?
 - Given that we now have a [POC of App Identity](https://github.com/finos-labs/fdc3-security), does the DA actually need more information about the apps? 
 - ..this is a big chunk of thinking!

**Comment by kriswest** [comment]
> Also, your diagram is missing the resend of WCP1Hello to the iFrame to restart the process with that. We may be able to eliminate that...
> 
> > I think I've raised this before (though maybe not on GitHub) but this causes a race condition between the iframe loading and the message arriving. It's better we don't have that step.

I believe we left that at using the onload event of the iframe (always available AFAIK, where it is not for cross-domain windows)).

> The reconnecting app would be sending over its identity details ...
> 
> Yes, I did consider this yesterday. I'm not sure there's really any security improvement by having multiple steps though. A determined spoofer could just read the messages and respond as if it were a desktop agent. But if you want to send all the appId/metadata through the message port, that could work..

Yes over the MessagePort is how its specified and it would be harder for a spoofer to eavesdrop on.

> App Starts, sending:
> - WCP1Hello adding the URL of the app, as discussed in the last meeting. (i.e. so we don't need WCP4Validate)

But we are likely to need it in future - we'd be making it more complex to update in future if we drop the step now.

> this is likely to have to work as a challenge-response, where the DA sends a message challenging the App to prove it's identity (encrypt this string for me using your private key) and the app responds.

WCP3Handshake could contain the challenge, WCP4ValidateIdentity the response, WCP5 the acknowledgement/error

**Comment by kriswest** [comment]
Yes can move it - but not on dropping the Validate message entirely (as we'll very likely need it for a challenge/response later - I realise not much data will be sent currently).

**Comment by kriswest** [comment]
To clarify - I think sharing the URL over the WindowProxy may be ok, although it still a possible info leak... I would be very wary of moving any of the other id data and shared secrets out - so instance identity details still get sent in the WCPValidate step. To keep it together we should probably have the identity URL sent in that step as well. I don't mind it _also_ being in WCP1Hello if thats useful.

**Comment by kriswest** [comment]
@robmoffat hows this:? a628009100d6d7e53c9283f0a58ca34e954a7e30
Obviously, we're sending the identity URL twice... but to different targets (`window.postMessage` / `messagePort.postMessage`) so I think thats (perhaps) as it should be?
