### ISSUE TITLE
Question: addEventListener() type parameter conflict

### ISSUE THREAD

**Issue by Charlotte981** [finos/FDC3#1348]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

I was attempting to add the new addEventListener() function to our desktop agent implementation and I noticed that there appears to be some conflict between the types defined in the main FDC3 specification and those defined in the Browser Types file. The FDC3 spec specifies that the consumer can pass null as the type parameter for addEventListener() to receive all event types, but the addEventListenerRequestPayload defined in Browser Types only accepts "USER_CHANNEL_CHANGED" as a type value. I was wondering if this was intentional or not?

**Comment by kriswest** [comment]
Hi @Charlotte981 yes that is intentional. We originally proposed to create a listener just for channel changed events (i.e. `addChannelChangedListener`), but when discussed at a [Standards Working Group meeting](https://github.com/finos/FDC3/issues/1160) there was consensus that we are likely to create more events in the future and it made sense to create something more extensible - hence we added `addEventListener` with a type field (matching the pattern used in the HTML Standard's APIs).

One additional event type that has been suggested (but not yet implemented) is for something relating to a connection to the Desktop Agent, which for some implementations might be remote and vulnerable to issues with the internet connection, so there might be connected/disconnected events in future. Similarly, connection to a Desktop Agent Bridge might come with events.

We've now also agreed to match the PrivateChannel events to this pattern, so there is an `addEventListener` there that supports 3 types, see:
- https://fdc3.finos.org/docs/next/api/ref/PrivateChannel#addeventlistener
- https://fdc3.finos.org/docs/next/api/ref/Events#privatechannelevent

**Comment by Charlotte981** [comment]
Sorry if I am misunderstanding you, but I meant to ask whether or not the type field for addEventListenerRequestPayload is also supposed to take null as a value since this is a potential input to the addEventListener() function? Or whether the intention is that on being passed the null value for the type parameter, the desktop agent sends out separate addEventListenerRequests for each FDC3EventType?

**Comment by kriswest** [comment]
Ah, it was me misunderstanding you in that case, apologies! You've identified a flaw in that message which I've just corrected in e18792dac0818d6419ea65264ddaa36e415aa04c
`null` is now a valid value for the `payload.type` field in `addEventListenerRequest`

Hopefully, this now adequately  answers your question!

**Comment by Charlotte981** [comment]
Excellent thank you
