### ISSUE TITLE
Question: how to return the appIdentifier from agent.open()

### ISSUE THREAD

**Issue by Roaders** [finos/FDC3#1408]
### Question Area
 - [ ] App Directory
 - [x] API
 - [ ] Context Data
 - [ ] Intents
 - [ ] Use Cases
 - [ ] Other

### Question

Thinking about how the root agent opens a new window does the resolution of the promise returned from `agent.open()` indicate that the new app is up and running and has successfully connected to the Desktop Agent or is the promise returned before proxy agent initialization has completed?

What happens if the new app doesn't connect to the desktop agent. Perhaps it only calls `getAgent()` later in it's lifecycle due to user interaction or perhaps it never calls `getAgent()`.

Is there any guidance how the desktop agent is supposed to link the action of launching a new app (lets say by opening a new window) and the action of the new app calling `getAgent()`. How does the instanceId generated by the desktop agent as part of the handshake get matched up to the pending `agent.open()` request?

I am thinking of scenarios where there might be multiple open commands in play at once and it might not be clear which handshake belongs to which `window.open()` request.

**Comment by kriswest** [comment]
This is poorly covered in the Standard's documentation, but the correct answer can be derived from that documentation - specifically the Error enumerations. Both methods of launching an application (`open` and `raiseIntent`) have specified error enumerations that include errors relating to the delivery of context to the application, which the respective promise should be rejected with if they can't achieve that. I.e.:

- [OpenError.AppTimeout](https://fdc3.finos.org/docs/api/ref/Errors#openerror)
- [ResolveError.IntentDeliveryFailed](https://fdc3.finos.org/docs/api/ref/Errors#resolveerror)

Hence, (at least in situations where you need to deliver context to the app) these functions cannot resolve (with the `AppIdentifier` or `IntentResolution`)until the relevant context listener or intent listener has been added by the application or you hit a timeout.

If no context is being passed with the call to fdc3.open, then there's nothing to wait for and you can return earlier I guess - I would suggest making sure the app is running, if not reject with `OpenError.ErrorOnLaunch`.

This could/should be clarified in the documentation - hence feel free to convert this issue into a request for that clarification and I can have a go at it later in the month.

**Comment by Roaders** [comment]
Thanks Kris but my question was not around error handling or particularly around sending of context.

Imagine I had an app with 4 iframes that I can load apps into. I want to load 4 graphs for 4 different instruments and I want each instrument displayed in the correct window. I send the 4 open window commands before any of the apps have loaded and executed `getAgent()`. The sequence diagram might look like this:

![image](https://github.com/user-attachments/assets/93de94d6-5289-43c9-a20b-bb56ebb89559)

When the first `getAgent()` call is received by the Desktop Agent you don't have any idea which request this is relation to. You might assume that the apps load in the order that they initiated but this is not going to be the case every time.

We need to be able to link the open request to the getAgent() request so that we send the context to the right app and return the instasnceId of the app in the top left iframe to the promise that was created when loading an app into that iframe - and to return the result to the correct getResult() promise.

I hope that makes it a bit easier to understand the problem I am trying to solve. I am not sure what the solution is.

**Comment by kriswest** [comment]
Hi @Roaders, ok I see the issue: When you have multiple concurrent or at least overlapping requests to open apps, how do you identify which request to connect if coming in from each. 

The messages themselves don't help with this - but we have discussed how an implementation would solve this. When you start a window with window.open you receive back a WindowProxy, while if you create an iframe you should be able to access its `iframe.contentWindow` reference which is also a WindowProxy. Then when the DA receives `message` events sent via `postMessage` on its window reference made by getAgent (WCP1Hello) the `source` (see https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/source) should also be a WindowProxy. These objects are directly comparable for equality (I'm struggling to find something to back that up in the [HTML Living Standard](https://html.spec.whatwg.org/multipage/nav-history-apis.html#the-windowproxy-exotic-object) - but it is something that was tested in multiple browsers and seems fundamental to them - @novavi may be able to add more info). 

Hence, if the DA is creating the frames or windows, it should be able to tell which inbound connection relates to each copy of the app that it started and should retain that info (along with the generated `instanceId` and `instanceUuid` as it creates and returns MessagePorts to communicate with them (note that messages over ports will set `source` to a reference to the port instead of the window, so you need to connect the instanceId/instanceUuid to the MessagePort when you create it).

Does that give you what you need to solve this? If so, I guess we should add a note on this section of the Web connection protocol: https://deploy-preview-1191--fdc3.netlify.app/docs/next/api/specs/browserDesktopAgents#responding-to-app-instance-connections---web-connection-protocol-wcp

**Comment by Roaders** [comment]
I was trying to get my head around a similar solution but couldn't quite get it to line up... Our implementation uses iframes to do messaging but I guess that the first message that the proxy window sends is still sent to the root window and it then recieves a message back telling it to open an iframe so I guess that this would still work....

There is still an issue around opening the app in a window that is not owned by the root window. There are ways around that though I guess but it will just be a bit harder to co-ordinate it

Thanks for the info. I'll have a go at implementing this.

**Comment by kriswest** [comment]
Good luck and let us know how you get on!
