### ISSUE TITLE
Generic List Context Object Schema - 2.0

### ISSUE THREAD

**Issue by markChartIQ** [finos/FDC3#177]
#178  Context Object Request

### Description of Problem:
List objects are currently created as a 1-off for each schema (ex. ContactList). As more context objects are added to FDC3, a generic list object will allow those implementing to have greater flexibility in messaging. 

### Potential Solutions:
A suggested generic list object has been created for review

Mixed lists or collections of various objects are not supported in this object.

**Comment by chedzoir** [comment]
As was discussed earlier, a simple implementation of a list could be something like

```
export interface ContextList {
  
  // Set to Context List
  type: string;

  // type of objects that the list contains
  subType: string;

  // the entries in the list, all of which should be context items of the type defined in listOf
  entries: Context[];
  
}
```

An example could be

```
{
  "type":"fdc3.contextList",
  "subType": "fdc3.instrument",
  "entries":[
    {
      "type":"fdc3.instrument",
      "id":{
        "ticker":"GBPUSD"
      }
    },
    {
      "type":"fdc3.instrument",
      "id":{
        "ticker":"EURUSD"
      }
    }
  ]
}
```

Then when it comes to listening for a list of contexts, there's a couple of ways that it could be done

One would be to register intents and listeners with a context string of `fdc3.contextList<fdc3.instrument>` 

Alternatively, you could instead of a string use an object of the form

```
{
  "type":"fdc3.contextList",
  "subType": "fdc3.instrument"
}
```

The former is more elegant, but would need a little parsing on desktop agent start up / intent registration to make calls such as `raiseIntent(intent: string, context: Context, target?: string): Promise<IntentResolution>;` efficient. When those calls are made, we need to identify that the context is a context list and has a sub type that we'd need to look up. But if `Context` is more formally defined than it is now and if we change the signature to `raiseIntent(intent: string, context: Context|ContextList, target?: string): Promise<IntentResolution>;` then it becomes workable.

**Comment by kriswest** [comment]
@chedzoir thanks for your contribution, what you propose is cleaner than whats in the PR associated with this issue.

After discussion during the working group, there doesn't seem to be strong support for this proposal (theres only half-hearted support at here at Cosaic, we opened the original issue). Nor did there seem to be *significant* objections to continuing to construct list types such as instrumentList or portfolio as named types in their own right. Not implementing this change doesn't prevent any use cases, nor does it cause significant inconvenience (by adding the subtype to the type string we are effectively just creating a new named type anyway, desktop agents wouldn't actually need to parse out the subtype to work with it). 

Hence, we are of the opinion that this issue can be closed - or at least deprioritized for inclusion in FDC3 1.2. If you think otherwise, please do comment.
