### ISSUE TITLE
Ability to open an application via intents in a pre-defined location

### ISSUE THREAD

**Issue by hampshan** [finos/FDC3#332]
### Use Case:
When raising intents the default behaviour is to present the user with a list of applications that can serve that intent.  The user can then choose which of the matching applications to launch.  The user could be required to provide further input about where the application should be added (e.g. in a new window, or to a pre-existing window/browser window, etc.).

This process of choosing and launching new applications (e.g. for an application that shows ticket details) impedes the flow for what can be very common tasks.

### Workflow Description
It would be beneficial to be able to raise intents for a predetermined application (e.g. 'ViewTicket') with the option of also providing a location of where the application should open (e.g. a new or existing window) and potentially provide additional metadata.

### Workflow Examples
`const { source } = await fdc3.raiseIntent('ViewTicket', {context},  'ticket-app', <targetMetadata>)`

where `<targetMetadata>` examples could be:
`{ locationType: 'window', locationId: '<windowId>', position: 'right', height:400, width:400}`
`{ locationType: 'group', locationId: '<groupId>', position: 'bottom'}`

**Comment by kriswest** [comment]
Note from Standards Working Group meeting 22/04/2021:
Rather than changing the signature of the interop functions (`raiseIntent`, `open`) to add a targetMetadata object, its preferable to instead use the fact that the target can now be specified as an `AppMetadata` object and to add custom properties to that object (which is related to the AppD application definition and could bring similar custom config with it from the manifest/hostManifest). 

https://fdc3.finos.org/docs/next/api/ref/Metadata#appmetadata
Note AppMetadata doesn't currently include the manifest, we could add that and another element for manual overrides of/additions to the configuration

**Comment by kriswest** [comment]
@hampshan we're actively discussing #450 which I believe addresses the same (or at least) overlapping concerns in that it would allow you to target existing instances of applications. Do you have any opinions on the proposals given in that issue?

Expressing location information for a new window (if spawned by the raised intent or `fdc3.open`) is something that's been discussed in the past and relegated to an implementation concern - I'll recheck opinions on that today at the discussion group meeting #475

Would you be amenable to us continuing with #450 and splitting out specification of location information into a separate issue?

**Comment by kriswest** [comment]
Closing in favour of #450 (which deals with targeting existing app instances). 

Note many participants at the discussion group meeting (#475) expressed the opinion that FDC3 should avoid getting into 'window management'. @hampshan if you'd like to re-open that discussion please raise a new issue on that specific topic.
