### ISSUE TITLE
README update / Introductory materials

### ISSUE THREAD

**Issue by robmoffat** [finos/FDC3#750]
## Minor Issue
For a few other FINOS projects we are moving to a more friendly, beginner-centric form of the README, e.g.

https://github.com/finos/spring-bot
https://github.com/finos/morphir 

I think as we approach OSFF we should take a look at the existing README and try and do similar.  Whereas fdc3.finos.org does a great job of laying out the spec for developers, and a somewhat good job of marketing the project in terms of explaining who uses it, the README should be oriented at curious people trying to understand the basic questions of 
 - What is It?
 - Why is it important?
 - What are the benefits?
 - Getting started

There are loads of pre-existing resources around the internet about FDC3 we can draw on and link to to help answer these questions.

**Comment by rikoe** [comment]
The current README was very specifically created to follow the template mandated by the FINOS Standards project blueprint at the time.

However, I am not aware how much that has changed since (quite a bit it seems).

Happy to change it, but again, we should stick to a standard FINOS template as much as possible - is there one that represents the examples you refer to (e.g. Morphir)?

It is also worth pointing out that the current README serves a dual purpose - it is used on npmjs.com when publishing the [`@finos/fdc3` package](https://www.npmjs.com/package/@finos/fdc3). It can be decoupled of course, but they were combined to reduce the maintenance burden and divergence/discrepancies. Any changes made to the project README will therefore also affect the NPM package home page.

**Comment by robmoffat** [comment]
@rikoe thanks that's really useful background.  

Yes, the Morphir one is the template.  Also I included the spring-bot one for reference which I updated a few months back to match.

I am working on a PR here.  I might have something to show next week
