### ISSUE TITLE
RecipientsObject interface has un unnecessary required type property

### ISSUE THREAD

**Issue by bingenito** [finos/FDC3#854]
## Minor Issue
The RecipientsObject export used for fdc3.email has a required type property.  Perhaps the definition was copied from a context definition and was not removed.  If it is intended to be there, should it be a context type of fdc3.recipientobject and have a string constant defined?

### Area of Issue
[x] Context Data

**Comment by kriswest** [comment]
See https://github.com/finos/FDC3/issues/853 for more detail on why this object exists (TLDR; quicktype created it by merging `Contact` and `ContactList`). 

RecipientObject is a standalone interface created by the generator and technically it does need a required `type` property as it is not inheriting one from anywhere. That said the generated type is NOT ideal and we may wish to consider taking over manual creation of types or otherwise customizing type creation by quicktype (see http://blog.quicktype.io/customizing-quicktype/ for advice on what  is possible).

@bingenito can we close this issue and pursue improvements under one of the others?

**Comment by mistryvinay** [comment]
Will close this issue and link to related issue #853
