### ISSUE TITLE
appD pom files included in npm package are lacking license

### ISSUE THREAD

**Issue by bingenito** [finos/FDC3#996]
## Minor Issue
Inclusion of /src in npm packages is including the appD pom.xml(s) which have no licenses defined.  This is preventing onboarding of these npm packages to enterprise repositories that do license validation.

### Issue Description: 
Either license should be added to all the pom files or ideally excluding /src from the npm package.

- org.finos.fdc3.appd:appd-java-server-stubs
- org.finos.fdc3.appd:appd-jersey-client
- org.finos.fdc3.appd:appd-nodejs-server-stubs
- org.finos.fdc3.appd:appd-typescript-angular-client

Note that package managers identify these components as also being 1.0.0-SNAPSHOT due to the hardcodings.

**Comment by kriswest** [comment]
Thanks for flagging this @bingenito 

@rikoe @nkolba @openfin-johans @mattjamieson @mistryvinay @ggeorgievx @greyseer256 @robmoffat are any of you aware of anyone using these POM files to generate server stubs and clients in the wild? I've never heard of them being used, nor do I maintain them (although they do reference the appD spec file so presumably can generate up-to-date stubs/clients). 

Hence, any objection to removing them from the NPM module? Given that they are Maven POM files, inclusion in the NPM module is probably not intentional. I have no idea if they are used or even current as far as how you generate code from OpenAPI specs.

Also, do you have an opinion if the source files need to be included in the module at all? We include source maps already... We are currently including all of _dist_ and _src_ (and default files that always get included) via a [`files`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#files) entry, see: https://github.com/finos/FDC3/blob/428c12305324f288434088b863cce7c72c73b3e4/package.json#L17-L20C5

(current package size 121.1 kB)

Presumably, that entry could be customized to:

```json
  "files": [
    "dist"
  ],
```

(just include dist, package size 89.6kb) OR

```json
"files": [
    "dist",
    "src/api",
    "src/context",
    "src/intents",
    "src/app-directory/specification/appd.yaml"
  ],
```

(just include the appD schema, package size 114.9 kB) OR

```json
  "files": [
    "dist",
    "src/api",
    "src/context",
    "src/intents",
    "src/app-directory/specification"
  ],
```
(just excluded the files @bingenito flagged, package size 118.1 kB)

Thoughts?

**Comment by rikoe** [comment]
There are issues at play here:

1. Should the src folder be included in the npm package in the first place? This seems like a mistake.
2. The only relevant part of appd in the fdc3 repo, is the specification under `./src/app-directory/specification/appd.yaml` The rest is left over from the old days when FDC3 was turned into a single repo from multiple (and comes from https://github.com/FDC3/appd-api which was a Java appd sample/generated code).

Definitely these poms should be deleted, but also probably the sources shouldn't be included in the npm package.

**Comment by kriswest** [comment]
@rikoe I would tend to agree on not including the sources - I don't think there is a use case as they are of course available freely on github, source maps are included and the compiled types. Dropping them will reduce the bundle size by 25%

**Comment by kriswest** [comment]
@bingenito hopefully you saw that this was resolved and a new npm module is available, sans source files: https://www.npmjs.com/package/@finos/fdc3/v/2.0.2?activeTab=versions

**Comment by bingenito** [comment]
@kriswest Yes, thank you!  We were able to successfully onboard with no license issues.
